### ISSUE TITLE
Key words?

### ISSUE THREAD

**Issue by josuevalrob** [Vitaliy-1/DOCX2JATS#1]
Hi!

How should I text keywords in the docx file? 

thanks!

**Comment by Vitaliy-1** [comment]
DOCX is a an archive that contains files in OOXML format. This format doesn't support meta-tags like keywords, so I didn't parse them at all. I think, that all meta-tags should come from OJS (which we use to display our JATS XML). I'm planning in the future to develope a PHP-based parser that will include all meta from OJS.
But my main concern for now is a development of JATS XML to PDF converter, which will be released soon. It will include 2 variant -> the code for developers and the plugin to OJS 3.
