### ISSUE TITLE
Your sample file or any other do not pass the JATS validation

### ISSUE THREAD

**Issue by jotauses** [Vitaliy-1/DOCX2JATS#6]
Your example file: https://github.com/Vitaliy-1/DOCX2JATS/blob/master/article_english.xml

Validator: https://validator.jats4r.org/

**Comment by Vitaliy-1** [comment]
Hi @jotauses,

Yes, this document doesn't have DTD declaration. In other means it's valid. 
BTW, I'm dropping the support for this repository in favor of a new one parser written in PHP without 3rd party libraries: https://github.com/Vitaliy-1/docxToJats
More extensive documentation you can find in the OJS plugin that incorporates its functionality: https://github.com/Vitaliy-1/docxConverter

I'm not planning the whole JATS XML format, only DAR, which is a subset of JATS XML.

**Comment by Vitaliy-1** [comment]
Fixed for docxtojats: https://github.com/Vitaliy-1/docxToJats/commit/12ee41d36503b1f66763623bce07600513695e74
